version: 2
jobs:
  build-go112:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/mmarinm/sumologrus
    steps:
      - checkout
      - run: make ci


workflows:
  version: 2
  build:
    jobs:
      - build-go112
