version: 2
jobs:
  build-go112:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/segmentio/analytics-go
    steps:
      - checkout
      - run: make ci


workflows:
  version: 2
  build:
    jobs:
      - build-go112
